spring:
  profiles:
    active: dev
    include: common
  application:
    name: Seed
  http:
    encoding:
      force: true
      charset: utf-8 #http请求的字符编码
      enabled: true
      force-request: true
      force-response: true
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 16384MB
      max-request-size: 16384MB
  jpa:
    show-sql: true
#    database: oracle
  datasource:
      name: ss
#      url: jdbc:mysql://localhost:3306/pdc?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#      username: cdistc
      password: cd123321
#      url: jdbc:oracle:thin:@${oracle.database.url}:${oracle.database.port}:${oracle.database.sid}
#      username: ${oracle.database.username}
#      password: ${oracle.database.password}
#      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:sqlite:pdc.db

      driver-class-name: org.sqlite.JDBC
      type: com.zaxxer.hikari.HikariDataSource
#  quartz:
#    job-store-type: memory
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: test
#            instanceId: AUTO
#  quartz:
#    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: SeedClusteredScheduler
#            instanceId: AUTO
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 25
#            threadPriority: 5
#          jobStore:
#            misfireThreshold: 60000
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
#            useProperties: false
#            dataSource: ${spring.datasource.name}
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 20000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
    #    max-wait: -1
        max-idle: 8
        min-idle: 0


mybatis:
  mapper-locations: classpath:sql-map/*.xml
  type-aliases-package: io.github.cd871127.pdc.file.dto, io.github.cd871127.pdc.user.dto




hodgepodge:
  swagger:
    enable: false
#        test:
#          enable: true
#        quartz:
#          enable: false