server:
  port: 18888
  tomcat:
    uri-encoding: utf-8 #以Tomcat为web容器时的字符编码

#spring.devtools.restart.additional-paths=src/main/java
spring:
  http:
    encoding:
      force: true
      charset: utf-8 #http请求的字符编码
      enabled: true
      force-request: true
      force-response: true
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 128MB
      max-request-size: 128MB
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pdc?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: cdistc
      password: cd123321
      type: com.zaxxer.hikari.HikariDataSource
#  devtools:
#    restart:
#      additional-paths:


#  data:
    #mangodb的配置
#   mongodb:
#     authentication-database: carbonmiao # Authentication database name.
      #field-naming-strategy= # Fully qualified name of the FieldNamingStrategy to use.
      #grid-fs-database= # GridFS database name.
      #host: 127.0.0.1 # Mongo server host.
      #username: carbonmiao # Login user of the mongo server.
      #password: 111111 # Login password of the mongo server.
      #port: 27017 # Mongo server port.
      #只用下面的就可以了
#      #repositories:
#        #enabled: true # Enable Mongo repositories.
#      #uri: mongodb://carbonmiao:111111@localhost:27017/carbonmiao?authSource=carbonmiao&authMechanism=SCRAM-SHA-1 # Mongo database URI. When set, host and port are ignored.
#  devtools:
#    restart:
#      additional-paths:1

mybatis:
  mapper-locations: classpath:sql-mapper/*.xml
  type-aliases-package: anthony.cd.app.pdc
  #typeAliasesPackage: tk.mapper.model
#  mybatis.config：mybatis-config.xml配置文件的路径
#  mybatis.typeHandlersPackage：扫描typeHandlers的包
#  mybatis.checkConfigLocation：检查配置文件是否存在
#  mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE


